# Steve Triplett
# HARDsoftware
# March 2020

# SQLAlchemy implementation to create Object-Oritented scada_readings table in pre-prod

import sys

from sqlalchemy import create_engine
from sqlalchemy import Column, Integer, Float, String
from sqlalchemy.dialects.mysql import DECIMAL, TIMESTAMP, DATETIME, CHAR, TINYINT
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Scada_Signals(Base):
    __tablename__ = 'scada_signals'
    id = Column(Integer, primary_key=True)
    duid = Column(CHAR(20))
    signal_at = Column(DATETIME)
    dispatch_mw = Column(DECIMAL(precision=15, scale=5))
    six_sec_raise_mw = Column(DECIMAL(precision=15, scale=5))
    six_sec_lower_mw = Column(DECIMAL(precision=15, scale=5))
    sixty_sec_raise_mw = Column(DECIMAL(precision=15, scale=5))
    sixty_sec_lower_mw = Column(DECIMAL(precision=15, scale=5))
    five_min_raise_mw = Column(DECIMAL(precision=15, scale=5))
    five_min_lower_mw = Column(DECIMAL(precision=15, scale=5))
    dispatch_mw_flag = Column(TINYINT(4))
    six_sec_raise_flag = Column(TINYINT(4))
    six_sec_lower_flag = Column(TINYINT(4))
    sixty_sec_raise_flag = Column(TINYINT(4))
    sixty_sec_lower_flag = Column(TINYINT(4))
    five_min_raise_flag = Column(TINYINT(4))
    five_min_lower_flag = Column(TINYINT(4))


class Scada_Readings(Base):
    __tablename__ = 'scada_readings'
    id = Column(Integer, primary_key=True)
    duid = Column(CHAR(20))
    status_at = Column(DATETIME)
    dispatch_mw_flag = Column(TINYINT(4))
    dispatch_mw_flag_fb = Column(TINYINT(4))
    dispatch_mw = Column(DECIMAL(precision=15, scale=5))
    dispatch_mw_fb = Column(DECIMAL(precision=15, scale=5))
    active_power = Column(DECIMAL(precision=15, scale=5))
    six_sec_raise_flag = Column(TINYINT(4))
    six_sec_lower_flag = Column(TINYINT(4))
    sixty_sec_raise_flag = Column(TINYINT(4))
    sixty_sec_lower_flag = Column(TINYINT(4))
    five_min_raise_flag = Column(TINYINT(4))
    five_min_lower_flag = Column(TINYINT(4))
    six_sec_raise_flag_fb = Column(TINYINT(4))
    six_sec_lower_flag_fb = Column(TINYINT(4))
    sixty_sec_raise_flag_fb = Column(TINYINT(4))
    sixty_sec_lower_flag_fb = Column(TINYINT(4))
    five_min_raise_flag_fb = Column(TINYINT(4))
    five_min_lower_flag_fb = Column(TINYINT(4))
    six_sec_raise_mw = Column(DECIMAL(precision=15, scale=5))
    six_sec_lower_mw = Column(DECIMAL(precision=15, scale=5))
    sixty_sec_raise_mw = Column(DECIMAL(precision=15, scale=5))
    sixty_sec_lower_mw = Column(DECIMAL(precision=15, scale=5))
    five_min_raise_mw = Column(DECIMAL(precision=15, scale=5))
    five_min_lower_mw = Column(DECIMAL(precision=15, scale=5))
    six_sec_raise_mw_fb = Column(DECIMAL(precision=15, scale=5))
    six_sec_lower_mw_fb = Column(DECIMAL(precision=15, scale=5))
    sixty_sec_raise_mw_fb = Column(DECIMAL(precision=15, scale=5))
    sixty_sec_lower_mw_fb = Column(DECIMAL(precision=15, scale=5))
    five_min_raise_mw_fb = Column(DECIMAL(precision=15, scale=5))
    five_min_lower_mw_fb = Column(DECIMAL(precision=15, scale=5))
    unit_limit_dispatch_max_flag = Column(TINYINT(4))
    unit_limit_dispatch_min_flag = Column(TINYINT(4))
    unit_limit_dispatch_max_flag_fb = Column(TINYINT(4))
    unit_limit_dispatch_min_flag_fb = Column(TINYINT(4))
    unit_limit_dispatch_max_generator_limit = Column(DECIMAL(precision=15, scale=5))
    unit_limit_dispatch_min_generator_limit = Column(DECIMAL(precision=15, scale=5))
    unit_limit_dispatch_max_generator_limit_fb = Column(DECIMAL(precision=15, scale=5))
    unit_limit_dispatch_min_generator_limit_fb = Column(DECIMAL(precision=15, scale=5))
    number_gen_units_connected = Column(DECIMAL(precision=15, scale=5))
    seconds_until_dispatch_interval_end = Column(DECIMAL(precision=15, scale=5))
    dispatch_interval_timestamp_year = Column(DECIMAL(precision=15, scale=5))
    dispatch_interval_timestamp_month = Column(DECIMAL(precision=15, scale=5))
    dispatch_interval_timestamp_day = Column(DECIMAL(precision=15, scale=5))
    dispatch_interval_timestamp_hour = Column(DECIMAL(precision=15, scale=5))
    dispatch_interval_timestamp_minute = Column(DECIMAL(precision=15, scale=5))
    number_avial = Column(Integer)
    number_gen = Column(Integer)
    local_limit_mw = Column(DECIMAL(precision=15, scale=5))
    possible_power = Column(DECIMAL(precision=15, scale=5))
    forecast_power = Column(DECIMAL(precision=15, scale=5))
    met1_irradiance = Column(DECIMAL(precision=15, scale=5))
    met1_air_temperature = Column(DECIMAL(precision=15, scale=5))
    met1_surface_temperature = Column(DECIMAL(precision=15, scale=5))
    met1_wind_speed = Column(DECIMAL(precision=15, scale=5))
    met1_wind_direction = Column(DECIMAL(precision=15, scale=5))
    met2_irradiance = Column(DECIMAL(precision=15, scale=5))
    met2_air_temperature = Column(DECIMAL(precision=15, scale=5))
    met2_surface_temperature = Column(DECIMAL(precision=15, scale=5))
    met2_wind_speed = Column(DECIMAL(precision=15, scale=5))
    met2_wind_direction = Column(DECIMAL(precision=15, scale=5))
    CollGrp1_cb_status_open = Column(TINYINT(4))
    CollGrp1_cb_status_closed = Column(TINYINT(4))
    CollGrp2_cb_status_open = Column(TINYINT(4))
    CollGrp2_cb_status_closed = Column(TINYINT(4))
    CollGrp5_cb_status_open = Column(TINYINT(4))
    CollGrp5_cb_status_closed = Column(TINYINT(4))
    CollGrp6_cb_status_open = Column(TINYINT(4))
    CollGrp6_cb_status_closed = Column(TINYINT(4))
    CollGrp7_cb_status_open = Column(TINYINT(4))
    CollGrp7_cb_status_closed = Column(TINYINT(4))
    CollGrp8_cb_status_open = Column(TINYINT(4))
    CollGrp8_cb_status_closed = Column(TINYINT(4))
    CollGrp11_cb_status_open = Column(TINYINT(4))
    CollGrp11_cb_status_closed = Column(TINYINT(4))
    CollGrp12_cb_status_open = Column(TINYINT(4))
    CollGrp12_cb_status_closed = Column(TINYINT(4))
    cb_220kV_cp_status_open = Column(TINYINT(4))
    cb_220kV_cp_status_closed = Column(TINYINT(4))
    cb_33kV_Transformer1A_open = Column(TINYINT(4))
    cb_33kV_Transformer1A_closed = Column(TINYINT(4))
    cb_33kV_Transformer1B_open = Column(TINYINT(4))
    cb_33kV_Transformer1B_closed = Column(TINYINT(4))
    cb_1A_Incomer_No1_open = Column(TINYINT(4))
    cb_1A_Incomer_No1_closed = Column(TINYINT(4))
    cb_1A_Incomer_No2_open = Column(TINYINT(4))
    cb_1A_Incomer_No2_closed = Column(TINYINT(4))
    cb_1B_Incomer_No1_open = Column(TINYINT(4))
    cb_1B_Incomer_No1_closed = Column(TINYINT(4))
    cb_1B_Incomer_No2_open = Column(TINYINT(4))
    cb_1B_Incomer_No2_closed = Column(TINYINT(4))
    CollGrp1_number_available = Column(Integer)
    CollGrp1_number_generating = Column(Integer)
    CollGrp2_number_available = Column(Integer)
    CollGrp2_number_generating = Column(Integer)
    CollGrp5_number_available = Column(Integer)
    CollGrp5_number_generating = Column(Integer)
    CollGrp6_number_available = Column(Integer)
    CollGrp6_number_generating = Column(Integer)
    CollGrp7_number_available = Column(Integer)
    CollGrp7_number_generating = Column(Integer)
    CollGrp8_number_available = Column(Integer)
    CollGrp8_number_generating = Column(Integer)
    CollGrp11_number_available = Column(Integer)
    CollGrp11_number_generating = Column(Integer)
    CollGrp12_number_available = Column(Integer)
    CollGrp12_number_generating = Column(Integer)
    CollGrp1_active_power = Column(DECIMAL(precision=15, scale=5))
    CollGrp1_av_track_angle = Column(DECIMAL(precision=15, scale=5))
    CollGrp2_active_power = Column(DECIMAL(precision=15, scale=5))
    CollGrp2_av_track_angle = Column(DECIMAL(precision=15, scale=5))
    CollGrp5_active_power = Column(DECIMAL(precision=15, scale=5))
    CollGrp5_av_track_angle = Column(DECIMAL(precision=15, scale=5))
    CollGrp6_active_power = Column(DECIMAL(precision=15, scale=5))
    CollGrp6_av_track_angle = Column(DECIMAL(precision=15, scale=5))
    CollGrp7_active_power = Column(DECIMAL(precision=15, scale=5))
    CollGrp7_av_track_angle = Column(DECIMAL(precision=15, scale=5))
    CollGrp8_active_power = Column(DECIMAL(precision=15, scale=5))
    CollGrp8_av_track_angle = Column(DECIMAL(precision=15, scale=5))
    CollGrp11_active_power = Column(DECIMAL(precision=15, scale=5))
    CollGrp11_av_track_angle = Column(DECIMAL(precision=15, scale=5))
    CollGrp12_active_power = Column(DECIMAL(precision=15, scale=5))
    CollGrp12_av_track_angle = Column(DECIMAL(precision=15, scale=5))
    inverter1_status = Column(Integer)
    inverter1_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter1_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter2_status = Column(Integer)
    inverter2_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter2_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter3_status = Column(Integer)
    inverter3_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter3_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter4_status = Column(Integer)
    inverter4_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter4_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter5_status = Column(Integer)
    inverter5_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter5_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter6_status = Column(Integer)
    inverter6_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter6_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter7_status = Column(Integer)
    inverter7_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter7_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter8_status = Column(Integer)
    inverter8_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter8_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter9_status = Column(Integer)
    inverter9_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter9_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter10_status = Column(Integer)
    inverter10_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter10_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter11_status = Column(Integer)
    inverter11_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter11_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter12_status = Column(Integer)
    inverter12_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter12_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter13_status = Column(Integer)
    inverter13_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter13_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter14_status = Column(Integer)
    inverter14_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter14_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter15_status = Column(Integer)
    inverter15_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter15_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter16_status = Column(Integer)
    inverter16_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter16_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter17_status = Column(Integer)
    inverter17_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter17_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter18_status = Column(Integer)
    inverter18_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter18_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter19_status = Column(Integer)
    inverter19_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter19_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter20_status = Column(Integer)
    inverter20_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter20_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter21_status = Column(Integer)
    inverter21_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter21_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter22_status = Column(Integer)
    inverter22_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter22_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter23_status = Column(Integer)
    inverter23_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter23_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter24_status = Column(Integer)
    inverter24_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter24_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter25_status = Column(Integer)
    inverter25_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter25_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter26_status = Column(Integer)
    inverter26_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter26_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter27_status = Column(Integer)
    inverter27_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter27_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter28_status = Column(Integer)
    inverter28_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter28_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter29_status = Column(Integer)
    inverter29_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter29_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter30_status = Column(Integer)
    inverter30_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter30_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter31_status = Column(Integer)
    inverter31_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter31_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter32_status = Column(Integer)
    inverter32_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter32_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter33_status = Column(Integer)
    inverter33_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter33_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter34_status = Column(Integer)
    inverter34_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter34_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter35_status = Column(Integer)
    inverter35_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter35_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter36_status = Column(Integer)
    inverter36_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter36_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter37_status = Column(Integer)
    inverter37_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter37_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter38_status = Column(Integer)
    inverter38_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter38_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter39_status = Column(Integer)
    inverter39_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter39_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter40_status = Column(Integer)
    inverter40_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter40_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter41_status = Column(Integer)
    inverter41_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter41_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter42_status = Column(Integer)
    inverter42_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter42_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter43_status = Column(Integer)
    inverter43_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter43_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter44_status = Column(Integer)
    inverter44_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter44_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter45_status = Column(Integer)
    inverter45_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter45_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter46_status = Column(Integer)
    inverter46_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter46_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter47_status = Column(Integer)
    inverter47_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter47_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter48_status = Column(Integer)
    inverter48_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter48_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter49_status = Column(Integer)
    inverter49_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter49_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter50_status = Column(Integer)
    inverter50_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter50_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter51_status = Column(Integer)
    inverter51_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter51_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter52_status = Column(Integer)
    inverter52_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter52_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter53_status = Column(Integer)
    inverter53_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter53_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter54_status = Column(Integer)
    inverter54_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter54_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter55_status = Column(Integer)
    inverter55_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter55_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter56_status = Column(Integer)
    inverter56_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter56_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter57_status = Column(Integer)
    inverter57_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter57_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter58_status = Column(Integer)
    inverter58_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter58_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter59_status = Column(Integer)
    inverter59_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter59_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter60_status = Column(Integer)
    inverter60_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter60_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter61_status = Column(Integer)
    inverter61_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter61_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter62_status = Column(Integer)
    inverter62_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter62_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter63_status = Column(Integer)
    inverter63_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter63_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter64_status = Column(Integer)
    inverter64_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter64_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter65_status = Column(Integer)
    inverter65_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter65_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter66_status = Column(Integer)
    inverter66_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter66_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter67_status = Column(Integer)
    inverter67_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter67_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter68_status = Column(Integer)
    inverter68_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter68_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter69_status = Column(Integer)
    inverter69_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter69_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter70_status = Column(Integer)
    inverter70_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter70_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter71_status = Column(Integer)
    inverter71_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter71_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter72_status = Column(Integer)
    inverter72_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter72_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter73_status = Column(Integer)
    inverter73_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter73_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter74_status = Column(Integer)
    inverter74_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter74_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter75_status = Column(Integer)
    inverter75_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter75_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter76_status = Column(Integer)
    inverter76_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter76_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter77_status = Column(Integer)
    inverter77_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter77_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter78_status = Column(Integer)
    inverter78_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter78_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter79_status = Column(Integer)
    inverter79_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter79_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter80_status = Column(Integer)
    inverter80_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter80_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter81_status = Column(Integer)
    inverter81_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter81_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter82_status = Column(Integer)
    inverter82_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter82_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter83_status = Column(Integer)
    inverter83_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter83_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter84_status = Column(Integer)
    inverter84_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter84_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter85_status = Column(Integer)
    inverter85_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter85_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter86_status = Column(Integer)
    inverter86_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter86_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter87_status = Column(Integer)
    inverter87_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter87_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter88_status = Column(Integer)
    inverter88_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter88_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter89_status = Column(Integer)
    inverter89_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter89_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter90_status = Column(Integer)
    inverter90_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter90_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter91_status = Column(Integer)
    inverter91_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter91_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter92_status = Column(Integer)
    inverter92_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter92_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter93_status = Column(Integer)
    inverter93_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter93_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter94_status = Column(Integer)
    inverter94_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter94_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter95_status = Column(Integer)
    inverter95_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter95_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter96_status = Column(Integer)
    inverter96_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter96_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter97_status = Column(Integer)
    inverter97_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter97_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter98_status = Column(Integer)
    inverter98_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter98_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter99_status = Column(Integer)
    inverter99_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter99_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter100_status = Column(Integer)
    inverter100_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter100_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter101_status = Column(Integer)
    inverter101_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter101_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter102_status = Column(Integer)
    inverter102_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter102_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter103_status = Column(Integer)
    inverter103_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter103_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter104_status = Column(Integer)
    inverter104_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter104_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter105_status = Column(Integer)
    inverter105_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter105_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter106_status = Column(Integer)
    inverter106_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter106_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter107_status = Column(Integer)
    inverter107_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter107_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter108_status = Column(Integer)
    inverter108_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter108_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter109_status = Column(Integer)
    inverter109_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter109_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter110_status = Column(Integer)
    inverter110_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter110_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter111_status = Column(Integer)
    inverter111_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter111_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter112_status = Column(Integer)
    inverter112_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter112_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter113_status = Column(Integer)
    inverter113_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter113_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter114_status = Column(Integer)
    inverter114_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter114_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter115_status = Column(Integer)
    inverter115_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter115_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter116_status = Column(Integer)
    inverter116_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter116_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter117_status = Column(Integer)
    inverter117_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter117_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter118_status = Column(Integer)
    inverter118_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter118_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter119_status = Column(Integer)
    inverter119_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter119_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter120_status = Column(Integer)
    inverter120_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter120_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter121_status = Column(Integer)
    inverter121_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter121_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter122_status = Column(Integer)
    inverter122_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter122_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter123_status = Column(Integer)
    inverter123_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter123_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter124_status = Column(Integer)
    inverter124_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter124_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter125_status = Column(Integer)
    inverter125_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter125_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter126_status = Column(Integer)
    inverter126_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter126_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter127_status = Column(Integer)
    inverter127_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter127_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter128_status = Column(Integer)
    inverter128_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter128_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter129_status = Column(Integer)
    inverter129_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter129_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter130_status = Column(Integer)
    inverter130_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter130_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter131_status = Column(Integer)
    inverter131_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter131_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter132_status = Column(Integer)
    inverter132_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter132_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter133_status = Column(Integer)
    inverter133_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter133_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter134_status = Column(Integer)
    inverter134_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter134_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter135_status = Column(Integer)
    inverter135_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter135_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter136_status = Column(Integer)
    inverter136_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter136_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter137_status = Column(Integer)
    inverter137_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter137_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter138_status = Column(Integer)
    inverter138_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter138_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter139_status = Column(Integer)
    inverter139_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter139_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter140_status = Column(Integer)
    inverter140_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter140_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter141_status = Column(Integer)
    inverter141_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter141_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter142_status = Column(Integer)
    inverter142_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter142_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter143_status = Column(Integer)
    inverter143_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter143_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter144_status = Column(Integer)
    inverter144_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter144_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter145_status = Column(Integer)
    inverter145_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter145_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter146_status = Column(Integer)
    inverter146_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter146_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter147_status = Column(Integer)
    inverter147_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter147_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter148_status = Column(Integer)
    inverter148_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter148_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter149_status = Column(Integer)
    inverter149_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter149_accum_energy = Column(DECIMAL(precision=15, scale=5))
    inverter150_status = Column(Integer)
    inverter150_active_power = Column(DECIMAL(precision=15, scale=5))
    inverter150_accum_energy = Column(DECIMAL(precision=15, scale=5))


def main(args):
    # Create db tables. Create engine that stores data into db, in this case connected to Kiamal Pre-Prod MySQL db
    # NOTE: Examples of old infra connections as well

    try:
        # old preprod
        # engine = create_engine('mysql+pymysql://parser:<password>@10.1.140.220/infolite')
        # old prod
        # engine = create_engine('mysql+pymysql://parser:<password>@10.1.140.22/infolite')
        # engine = create_engine(args[1])
       # new preprod for Kiamal
        engine = create_engine('mysql+pymysql://parser:B3@9ood^^4N@10.2.28.22/infolite')

        # Create all tables in engine, equivalent to 'create table' statements in raw SQL
        Base.metadata.create_all(engine)

    except Exception as e:
        print("SJT - the exception {} occurred".format(e))


if __name__ == '__main__':
    main(sys.argv)
